version: '3'

services:
  proxy:
    ports: 
      - "8080:8080"
    image: nginx:1.15.2
    networks: 
      - frontend
  web:
    env_file: env.env
    build:
      context: ./dir
      dockerfile: Dockerfile-alternate
      args: 
        - MyARG=NicoAsArg
    ports:
      - "5000:5000"
    volumes:
      - .:/config
    networks: 
      - database
      - frontend
  redis:
    image: redis
    networks: 
      - database

networks:
  database:
  frontend:

